export const artists = [
{ id: "112", name:"112" },
{ id: "702", name:"702" },,
{ id: "1-of-the-girls", name:"1 of The Girls" },
{ id: "2nd-nature", name:"2nd Nature" },
{ id: "3-2-da-lef", name:"3-2-Da-Lef" },
{ id: "3lw", name:"3LW" },
{ id: "3pc.", name:"3pc." },
{ id: "3rd-storee", name:"3rd Storee" },
{ id: "3t", name:"3T" },
{ id: "52nd-street", name:"52nd Street" },
{ id: "aaliyah", name:"Aaliyah" },
{ id: "aaron-hall", name:"Aaron Hall" },
{ id: "ac-black", name:"AC Black" },
{ id: "adina-howard", name:"Adina Howard" },
{ id: "after-7", name:"After 7" },
{ id: "aka-brown", name:"Aka Brown" },
{ id: "al-b.-sure", name:"Al B. Sure" },
{ id: "alex-mali", name:"Alex Mali" },
{ id: "alex-vaughn", name:"Alex Vaughn" },
{ id: "alexander-o'-neal", name:"Alexander O' Neal" },
{ id: "alicia-keys", name:"Alicia Keys" },
{ id: "alyson-williams", name:"Alyson Williams" },
{ id: "ama", name:"Ama" },
{ id: "amber-mark", name:"Amber Mark" },
{ id: "ambre", name:"Ambre" },
{ id: "amel-larrieux", name:"Amel Larrieux" },
{ id: "amerie", name:"Amerie" },
{ id: "amina-buddafly", name:"Amina Buddafly" },
{ id: "angela-winbush", name:"Angela Winbush" },
{ id: "angie-stone-", name:"Angie Stone " },
{ id: "anita-baker", name:"Anita Baker" },
{ id: "anita-pointer", name:"Anita Pointer" },
{ id: "anjel", name:"Anjel" },
{ id: "ann-marie", name:"Ann Marie" },
{ id: "another-bad-creation", name:"Another Bad Creation" },
{ id: "another-level", name:"Another Level" },
{ id: "answered-questions", name:"Answered Questions" },
{ id: "anthony-hamilton", name:"Anthony Hamilton" },
{ id: "aqyila", name:"Aqyila" },
{ id: "aretha-franklin", name:"Aretha Franklin" },
{ id: "ari-lennox", name:"Ari Lennox" },
{ id: "arnishia-king", name:"Arnishia King" },
{ id: "ashanti", name:"Ashanti" },
{ id: "asia-cruise", name:"Asia Cruise" },
{ id: "at-last", name:"At Last" },
{ id: "athena-cage", name:"Athena Cage" },
{ id: "atl", name:"ATL" },
{ id: "attitude", name:"Attitude" },
{ id: "audrey-wheeler", name:"Audrey Wheeler" },
{ id: "august-alsina", name:"August Alsina" },
{ id: "avant", name:"Avant" },
{ id: "az-yet", name:"Az Yet" },
{ id: "b.a.d.-band", name:"B.A.D. Band" },
{ id: "b2k", name:"B2K" },
{ id: "b5", name:"B5" },
{ id: "babyface", name:"Babyface" },
{ id: "barry-white", name:"Barry White" },
{ id: "bc", name:"Bc" },
{ id: "before-dark", name:"Before Dark" },
{ id: "bel-biv-devoe", name:"Bel Biv Devoe" },
{ id: "beyonce", name:"Beyonce" },
{ id: "bilial", name:"Bilial" },
{ id: "black-buddafly", name:"Black Buddafly" },
{ id: "black-n-wild", name:"Black N Wild" },
{ id: "blackgirl", name:"Blackgirl" },
{ id: "blackstreet", name:"Blackstreet" },
{ id: "blaque", name:"Blaque" },
{ id: "blue-cantrell", name:"Blue Cantrell" },
{ id: "bobby-brown", name:"Bobby Brown" },
{ id: "bobby-valentino-(bobby-v.)", name:"Bobby Valentino (Bobby V.)" },
{ id: "body", name:"Body" },
{ id: "boyz-ii-men", name:"Boyz II Men" },
{ id: "brandy", name:"Brandy" },
{ id: "brent-faiyaz", name:"Brent Faiyaz" },
{ id: "brian-mcknight", name:"Brian McKnight" },
{ id: "brooke-valentine", name:"Brooke Valentine" },
{ id: "brownstone", name:"Brownstone" },
{ id: "brutha", name:"Brutha" },
{ id: "bryson-tiller", name:"Bryson Tiller" },
{ id: "bt", name:"BT" },
{ id: "by-all-means", name:"By All Means" },
{ id: "camille-douglas", name:"Camille Douglas" },
{ id: "candace-boyd", name:"Candace Boyd" },
{ id: "candy-hill", name:"Candy Hill" },
{ id: "carl-thomas", name:"Carl Thomas" },
{ id: "caron-wheeler", name:"Caron Wheeler" },
{ id: "case", name:"Case" },
{ id: "cassie", name:"Cassie" },
{ id: "cece-penniston", name:"Cece Penniston" },
{ id: "chaka-khan", name:"Chaka Khan" },
{ id: "changing-faces", name:"Changing Faces" },
{ id: "chantay-savage", name:"Chantay Savage" },
{ id: "chante-moore", name:"Chante Moore" },
{ id: "chapter-4", name:"Chapter 4" },
{ id: "che-fu", name:"Che Fu" },
{ id: "cherish", name:"Cherish" },
{ id: "cherrelle", name:"Cherrelle" },
{ id: "cheryl-lynn", name:"Cheryl Lynn" },
{ id: "chico-debarge", name:"Chico Debarge" },
{ id: "chisette-michelle", name:"Chisette Michelle" },
{ id: "chloe-x-halle", name:"Chloe X Halle" },
{ id: "chris-brown", name:"Chris Brown" },
{ id: "chris-jasper", name:"Chris Jasper" },
{ id: "chris-walker", name:"Chris Walker" },
{ id: "christina-millian", name:"Christina Millian" },
{ id: "christión", name:"Christión" },
{ id: "christopher-wiliams", name:"Christopher Wiliams" },
{ id: "chuckii-booker", name:"Chuckii Booker" },
{ id: "city-high", name:"City High" },
{ id: "classic-example", name:"Classic Example" },
{ id: "co-ed", name:"Co-Ed" },
{ id: "coco-jones", name:"Coco Jones" },
{ id: "coko", name:"Coko" },
{ id: "color-me-badd", name:"Color Me Badd" },
{ id: "coming-of-age", name:"Coming of Age" },
{ id: "countess-vaughn", name:"Countess Vaughn" },
{ id: "craig-david", name:"Craig David" },
{ id: "d'angelo", name:"D'Angelo" },
{ id: "d'atra-hicks", name:"D'Atra Hicks" },
{ id: "dalvin-degrate", name:"Dalvin Degrate" },
{ id: "damage", name:"Damage" },
{ id: "damozel", name:"damozel" },
{ id: "daniel-caesar", name:"Daniel Caesar" },
{ id: "danny-boy", name:"Danny Boy" },
{ id: "dave-hollister", name:"Dave Hollister" },
{ id: "davina", name:"Davina" },
{ id: "day26", name:"Day26" },
{ id: "debarge", name:"Debarge" },
{ id: "deborah-cox", name:"Deborah Cox" },
{ id: "dee-dee-wilde", name:"Dee Dee Wilde" },
{ id: "déjà", name:"Déjà" },
{ id: "dejah", name:"Dejah" },
{ id: "demetria-mckinney", name:"Demetria Mckinney" },
{ id: "denise-stewart", name:"Denise Stewart" },
{ id: "destiny's-child", name:"Destiny's Child" },
{ id: "dg", name:"dG" },
{ id: "diana-ross", name:"Diana Ross" },
{ id: "donell-jones", name:"Donell Jones" },
{ id: "donell-rush", name:"Donell Rush" },
{ id: "donna-summer", name:"Donna Summer" },
{ id: "donnie", name:"Donnie" },
{ id: "doramus", name:"Doramus" },
{ id: "dorian-harewood", name:"Dorian Harewood" },
{ id: "dream", name:"DREAM" },
{ id: "dru-hill", name:"Dru Hill" },
{ id: "dvsn", name:"dvsn" },
{ id: "dwele", name:"Dwele" },
{ id: "eamon", name:"Eamon" },
{ id: "eboni-foster", name:"Eboni Foster" },
{ id: "el-debarge", name:"El Debarge" },
{ id: "elate", name:"Elate" },
{ id: "elûsion", name:"Elûsion" },
{ id: "en-vogue", name:"En Vogue" },
{ id: "eol", name:"EOL" },
{ id: "eric-bellinger", name:"Eric Bellinger" },
{ id: "eric-benet", name:"Eric Benet" },
{ id: "eric-gable", name:"Eric Gable" },
{ id: "errol-brown", name:"Errol Brown" },
{ id: "erykah-badu", name:"Erykah Badu" },
{ id: "essi", name:"Essi" },
{ id: "estelle", name:"Estelle" },
{ id: "ester-dean", name:"Ester Dean" },
{ id: "eternal", name:"Eternal" },
{ id: "eu", name:"EU" },
{ id: "eugene-wilde", name:"Eugene Wilde" },
{ id: "evelyn-'champagne'-king", name:"Evelyn 'Champagne' King" },
{ id: "ex-girlfriend", name:"Ex-Girlfriend" },
{ id: "fabu", name:"Fabu" },
{ id: "faith-evans", name:"Faith Evans" },
{ id: "fantasia", name:"Fantasia" },
{ id: "farrah-franklin", name:"Farrah Franklin" },
{ id: "felicia-adams-", name:"Felicia Adams " },
{ id: "feloney-davis", name:"Feloney Davis" },
{ id: "fetty-wap", name:"Fetty Wap" },
{ id: "fifth-of-heaven", name:"Fifth of Heaven" },
{ id: "flo", name:"FLO" },
{ id: "floetry", name:"Floetry" },
{ id: "fo-sho", name:"Fo Sho" },
{ id: "frank-ocean", name:"Frank Ocean" },
{ id: "frankie", name:"Frankie" },
{ id: "frankie-j", name:"Frankie J" },
{ id: "freddie-jackson", name:"Freddie Jackson" },
{ id: "game", name:"GAME" },
{ id: "gary-adkins", name:"Gary Adkins" },
{ id: "gerald-levert", name:"Gerald Levert" },
{ id: "ghost-town-dj's", name:"Ghost Town DJ's" },
{ id: "gina-thompson", name:"Gina Thompson" },
{ id: "ginuwine", name:"Ginuwine" },
{ id: "glasswurk", name:"Glasswurk" },
{ id: "glenn-jones", name:"Glenn Jones" },
{ id: "glenn-lewis", name:"Glenn Lewis" },
{ id: "goapele", name:"Goapele" },
{ id: "good-2-go", name:"Good 2 Go" },
{ id: "groove-theory", name:"Groove Theory" },
{ id: "guinn", name:"Guinn" },
{ id: "guy", name:"Guy" },
{ id: "gyrl", name:"Gyrl" },
{ id: "h-town", name:"H-Town" },
{ id: "heather-headley", name:"Heather Headley" },
{ id: "hi-five", name:"Hi-Five" },
{ id: "highland-place-mobsters", name:"Highland Place Mobsters" },
{ id: "horace-brown", name:"Horace Brown" },
{ id: "houston", name:"Houston" },
{ id: "howard-hewett", name:"Howard Hewett" },
{ id: "hugh-'huriah'-boynton", name:"Hugh 'Huriah' Boynton" },
{ id: "i-15", name:"I-15" },
{ id: "iamddb", name:"IAMDDB" },
{ id: "ideal", name:"Ideal" },
{ id: "igelese", name:"Igelese" },
{ id: "ii-d-extreme", name:"II D Extreme" },
{ id: "iii-frum-tha-soul", name:"III Frum Tha Soul" },
{ id: "immature", name:"Immature" },
{ id: "inayah", name:"Inayah" },
{ id: "india.aire", name:"India.Aire" },
{ id: "inoj", name:"INOJ" },
{ id: "intro", name:"Intro" },
{ id: "isyss", name:"ISYSS" },
{ id: "j.-cozier", name:"J. Cozier" },
{ id: "j.-holiday", name:"J. Holiday" },
{ id: "j.-valentine", name:"J. Valentine" },
{ id: "j'son", name:"J'son" },
{ id: "jackie-wilson", name:"Jackie Wilson" },
{ id: "jade", name:"Jade" },
{ id: "jagged-edge", name:"Jagged Edge" },
{ id: "jaheim", name:"Jaheim" },
{ id: "jamelia", name:"Jamelia" },
{ id: "james-ingram", name:"James Ingram" },
{ id: "jamie-foxx", name:"Jamie Foxx" },
{ id: "jamm", name:"Jamm" },
{ id: "janelle-monae", name:"Janelle Monae" },
{ id: "janet-jackson", name:"Janet Jackson" },
{ id: "janine", name:"Janine" },
{ id: "jasmine-v", name:"Jasmine V" },
{ id: "jason-weaver", name:"Jason Weaver" },
{ id: "jaydon", name:"JayDon" },
{ id: "jaz-karis", name:"Jaz Karis" },
{ id: "jeff-redd", name:"Jeff Redd" },
{ id: "jeffery-valentine", name:"Jeffery Valentine" },
{ id: "jenevieve", name:"Jenevieve" },
{ id: "jennifer-hudson", name:"Jennifer Hudson" },
{ id: "jeremih", name:"Jeremih" },
{ id: "jermaine-jackson", name:"Jermaine Jackson" },
{ id: "jerome", name:"Jerome" },
{ id: "jersey-ave.", name:"Jersey Ave." },
{ id: "jesse-boykins-iii", name:"Jesse Boykins III" },
{ id: "jesse-powell", name:"Jesse Powell" },
{ id: "jewell", name:"Jewell" },
{ id: "jhene-aiko", name:"Jhene Aiko" },
{ id: "jill-scott", name:"Jill Scott" },
{ id: "jo-jo-robinson", name:"Jo Jo Robinson" },
{ id: "jodeci", name:"Jodeci" },
{ id: "jody-watley", name:"Jody Watley" },
{ id: "joe", name:"Joe" },
{ id: "joe-tex-ii", name:"Joe Tex II" },
{ id: "john-legend", name:"John Legend" },
{ id: "john-white", name:"John White" },
{ id: "johnny-gill", name:"Johnny Gill" },
{ id: "johnny-kemp", name:"Johnny Kemp" },
{ id: "jojo", name:"JoJo" },
{ id: "jon-b.", name:"Jon B." },
{ id: "jous", name:"Jous" },
{ id: "joyce-wrice", name:"Joyce Wrice" },
{ id: "js", name:"JS" },
{ id: "julie-dexter", name:"Julie Dexter" },
{ id: "julie-roberts", name:"Julie Roberts" },
{ id: "june-pointer", name:"June Pointer" },
{ id: "k-ci-&-jojo", name:"K-Ci & Jojo" },
{ id: "k.-michelle", name:"K. Michelle" },
{ id: "k.p.-&-envyi", name:"K.P. & Envyi" },
{ id: "karina", name:"Karina" },
{ id: "karyn-white", name:"Karyn White" },
{ id: "kashif", name:"Kashif" },
{ id: "kathy-sledge", name:"Kathy Sledge" },
{ id: "katzz", name:"Katzz" },
{ id: "kaycee-grogan", name:"Kaycee Grogan" },
{ id: "kcm", name:"KCM" },
{ id: "kehlani", name:"Kehlani" },
{ id: "keisha-white", name:"Keisha White" },
{ id: "keith-floyd", name:"Keith Floyd" },
{ id: "keith-sweat", name:"Keith Sweat" },
{ id: "keith-washington", name:"Keith Washington" },
{ id: "keke-palmer", name:"Keke Palmer" },
{ id: "keke-wyatt", name:"Keke Wyatt" },
{ id: "kelela", name:"Kelela" },
{ id: "kelis", name:"Kelis" },
{ id: "kelly-price", name:"Kelly Price" },
{ id: "kelly-rowland", name:"Kelly Rowland" },
{ id: "kem", name:"Kem" },
{ id: "kendra-jae", name:"Kendra Jae" },
{ id: "kenneth-mangram", name:"Kenneth Mangram" },
{ id: "kenny-smith", name:"Kenny Smith" },
{ id: "keri-hilson", name:"Keri Hilson" },
{ id: "kevon-edmonds", name:"Kevon Edmonds" },
{ id: "keyshia-cole", name:"Keyshia Cole" },
{ id: "kimberly-scott", name:"Kimberly Scott" },
{ id: "kindred-the-family-soul", name:"Kindred the Family Soul" },
{ id: "kulcha", name:"kulcha" },
{ id: "kut-klose", name:"Kut Klose" },
{ id: "la-toya-jackson", name:"La Toya Jackson" },
{ id: "lade-bac", name:"Lade Bac" },
{ id: "lalah-hathaway", name:"Lalah Hathaway" },
{ id: "latif", name:"Latif" },
{ id: "latocha-scott", name:"LaTocha Scott" },
{ id: "latoiya-williams", name:"Latoiya Williams" },
{ id: "latrelle", name:"Latrelle" },
{ id: "lauryn-hill", name:"Lauryn Hill" },
{ id: "layton-greene", name:"Layton Greene" },
{ id: "ledisi", name:"Ledisi" },
{ id: "leela-james", name:"Leela James" },
{ id: "lemar", name:"Lemar" },
{ id: "les-nubians", name:"Les Nubians" },
{ id: "letoya-luckett", name:"LeToya Luckett" },
{ id: "levert", name:"Levert" },
{ id: "liane-v", name:"Liane V" },
{ id: "lil'-mo", name:"Lil' Mo" },
{ id: "link", name:"Link" },
{ id: "lo-key?", name:"Lo Key?" },
{ id: "lorenzo-smith", name:"Lorenzo Smith" },
{ id: "lucy-pearl", name:"Lucy Pearl" },
{ id: "luther-vandross", name:"Luther Vandross" },
{ id: "lyfe-jennings", name:"Lyfe Jennings" },
{ id: "macy-gray", name:"Macy Gray" },
{ id: "mahalia", name:"Mahalia" },
{ id: "mantronix", name:"Mantronix" },
{ id: "mariah-carey", name:"Mariah Carey" },
{ id: "mariah-the-scientist", name:"Mariah The Scientist" },
{ id: "mario", name:"Mario" },
{ id: "mario-winans", name:"Mario Winans" },
{ id: "mark-morrison", name:"Mark Morrison" },
{ id: "marques-houston", name:"Marques Houston" },
{ id: "marva-hicks", name:"Marva Hicks" },
{ id: "mary-j.-blige", name:"Mary J. Blige" },
{ id: "marzz", name:"Marzz" },
{ id: "mason", name:"Mason" },
{ id: "maxwell", name:"Maxwell" },
{ id: "maya-milan", name:"Maya Milan" },
{ id: "me-2-u", name:"Me 2 U" },
{ id: "me'shell-ndegéocello", name:"Me'shell Ndegéocello" },
{ id: "mel'isa-morgan", name:"Mel'isa Morgan" },
{ id: "melvin-riley", name:"Melvin Riley" },
{ id: "men-at-large", name:"Men at Large" },
{ id: "men-of-vizion", name:"Men of Vizion" },
{ id: "menageri", name:"Menageri" },
{ id: "methrone", name:"Methrone" },
{ id: "michael-jackson", name:"Michael Jackson" },
{ id: "michael-sterling", name:"Michael Sterling" },
{ id: "michel'le", name:"Michel'le" },
{ id: "michelle-williams", name:"Michelle Williams" },
{ id: "michon-young", name:"Michon Young" },
{ id: "midnight-starr", name:"Midnight Starr" },
{ id: "migual", name:"Migual" },
{ id: "mike-davis", name:"Mike Davis" },
{ id: "miki-howard", name:"Miki Howard" },
{ id: "mila-j", name:"Mila J" },
{ id: "milestone", name:"Milestone" },
{ id: "milira", name:"Milira" },
{ id: "millie-scott", name:"Millie Scott" },
{ id: "mind", name:"Mind" },
{ id: "mint-condition", name:"Mint Condition" },
{ id: "missez", name:"Missez" },
{ id: "mista", name:"Mista" },
{ id: "mo-b.-dick", name:"Mo B. Dick" },
{ id: "mokenstef", name:"MoKenStef" },
{ id: "molly-j", name:"Molly J" },
{ id: "mona-lisa", name:"Mona Lisa" },
{ id: "monica", name:"Monica" },
{ id: "monifah", name:"Monifah" },
{ id: "monteco", name:"Monteco" },
{ id: "montell-jordan", name:"Montell Jordan" },
{ id: "mullage", name:"Mullage" },
{ id: "muni-long", name:"Muni Long" },
{ id: "musiq-soulchild", name:"Musiq Soulchild" },
{ id: "mya", name:"Mya" },
{ id: "myron", name:"Myron" },
{ id: "n-deep", name:"N Deep" },
{ id: "n-phase", name:"N-Phase" },
{ id: "n-tyce", name:"N-Tyce" },
{ id: "n'dambi", name:"N'Dambi" },
{ id: "nais", name:"Nais" },
{ id: "natalie-la-rose", name:"Natalie La Rose" },
{ id: "natasha-ramos", name:"Natasha Ramos" },
{ id: "nate-dogg", name:"Nate Dogg" },
{ id: "ne-yo", name:"Ne-Yo" },
{ id: "new-edition", name:"New Edition" },
{ id: "next", name:"Next" },
{ id: "nicole-wray", name:"Nicole Wray" },
{ id: "nikita-germaine", name:"Nikita Germaine" },
{ id: "nivea", name:"Nivea" },
{ id: "normani", name:"Normani" },
{ id: "nuttin'-nyce", name:"Nuttin' Nyce" },
{ id: "old-skool", name:"Old Skool" },
{ id: "olivia", name:"Olivia" },
{ id: "omarion", name:"Omarion" },
{ id: "one-chance", name:"One Chance" },
{ id: "oran-'juice'-jones", name:"Oran 'Juice' Jones" },
{ id: "p.o.v.", name:"P.O.V." },
{ id: "pam-&-dodi", name:"Pam & Dodi" },
{ id: "paradise", name:"Paradise" },
{ id: "partynextdoor", name:"PARTYNEXTDOOR" },
{ id: "patrice-rushen-", name:"Patrice Rushen " },
{ id: "paula-deanda", name:"Paula Deanda" },
{ id: "phyllis-hyman", name:"Phyllis Hyman" },
{ id: "playa", name:"Playa" },
{ id: "pleasure-p", name:"Pleasure P" },
{ id: "portrait", name:"Portrait" },
{ id: "pressha", name:"Pressha" },
{ id: "pretty-ricky", name:"Pretty Ricky" },
{ id: "pretty-willie", name:"Pretty Willie" },
{ id: "prince", name:"Prince" },
{ id: "profyle", name:"Profyle" },
{ id: "projection", name:"Projection" },
{ id: "public-announcement", name:"Public Announcement" },
{ id: "purest-form", name:"Purest Form" },
{ id: "quindon", name:"Quindon" },
{ id: "r.-kelly", name:"R. Kelly" },
{ id: "raab", name:"Raab" },
{ id: "rachelle-ferrell", name:"Rachelle Ferrell" },
{ id: "raheem-devaughn", name:"Raheem Devaughn" },
{ id: "rahsaan-patterson", name:"Rahsaan Patterson" },
{ id: "ralph-tresvant", name:"Ralph Tresvant" },
{ id: "raphael-saadiq", name:"Raphael Saadiq" },
{ id: "ray-j", name:"Ray J" },
{ id: "ray-lavender", name:"Ray Lavender" },
{ id: "rayven-justice", name:"Rayven Justice" },
{ id: "ready-for-the-world", name:"Ready For The World" },
{ id: "rebbie-jackson", name:"Rebbie Jackson" },
{ id: "reel-tight", name:"Reel Tight" },
{ id: "rene-&-angela", name:"Rene & Angela" },
{ id: "renee-anderson", name:"Renee Anderson" },
{ id: "rick-james", name:"Rick James" },
{ id: "rl", name:"RL" },
{ id: "robbie-mychals", name:"Robbie Mychals" },
{ id: "rochelle-jordan", name:"Rochelle Jordan" },
{ id: "rome", name:"Rome" },
{ id: "ruben-studdard", name:"Ruben Studdard" },
{ id: "rude-boys", name:"Rude Boys" },
{ id: "ryan-leslie", name:"Ryan Leslie" },
{ id: "sa-deuce", name:"Sa Deuce" },
{ id: "sam-cooke", name:"Sam Cooke" },
{ id: "sam-salter", name:"Sam Salter" },
{ id: "samantha-mumba", name:"Samantha Mumba" },
{ id: "sammie", name:"Sammie" },
{ id: "sat-r-day", name:"Sat-R-Day" },
{ id: "sean-'barney'-thomas", name:"Sean 'Barney' Thomas" },
{ id: "sean-garrett", name:"Sean Garrett" },
{ id: "semi-mc", name:"Semi MC" },
{ id: "sevyn-streeter", name:"Sevyn Streeter" },
{ id: "shades", name:"Shades" },
{ id: "shai", name:"Shai" },
{ id: "shalamar-", name:"Shalamar " },
{ id: "shanice", name:"Shanice" },
{ id: "shannon", name:"Shannon" },
{ id: "shareefa", name:"Shareefa" },
{ id: "shawn-harris", name:"Shawn Harris" },
{ id: "shilo", name:"Shilo" },
{ id: "shirley-murdock", name:"Shirley Murdock" },
{ id: "shola-ama", name:"Shola Ama" },
{ id: "silk", name:"Silk" },
{ id: "sire", name:"Sire" },
{ id: "sisqo", name:"Sisqo" },
{ id: "sista", name:"Sista" },
{ id: "sister-sledge", name:"Sister Sledge" },
{ id: "skillz", name:"Skillz" },
{ id: "small-change", name:"Small Change" },
{ id: "smooth", name:"Smooth" },
{ id: "snoh-aalegra", name:"Snoh Aalegra" },
{ id: "sol", name:"Sol" },
{ id: "solange", name:"Solange" },
{ id: "soluna", name:"Soluna" },
{ id: "something-for-the-people", name:"Something For The People" },
{ id: "soul-2-soul", name:"Soul 2 Soul" },
{ id: "soul-4-real-", name:"Soul 4 Real " },
{ id: "soul-affect", name:"Soul Affect" },
{ id: "sounds-of-blackness", name:"Sounds of Blackness" },
{ id: "special-generation", name:"Special Generation" },
{ id: "static-major", name:"Static Major" },
{ id: "subway", name:"Subway" },
{ id: "sue-ann-carwell", name:"Sue Ann Carwell" },
{ id: "sugah", name:"Sugah" },
{ id: "summer-walker", name:"Summer Walker" },
{ id: "sunday", name:"Sunday" },
{ id: "sunshine-anderson", name:"Sunshine Anderson" },
{ id: "surface", name:"Surface" },
{ id: "suzi", name:"Suzi" },
{ id: "swae-lee", name:"Swae Lee" },
{ id: "sweet-obession", name:"Sweet Obession" },
{ id: "swv", name:"SWV" },
{ id: "syleena-johnson", name:"Syleena Johnson" },
{ id: "sza", name:"SZA" },
{ id: "t-pain", name:"T-Pain" },
{ id: "taggiz", name:"Taggiz" },
{ id: "tamar-braxton", name:"Tamar Braxton" },
{ id: "tamia", name:"Tamia" },
{ id: "tank", name:"Tank" },
{ id: "tanya-blount", name:"Tanya Blount" },
{ id: "taral", name:"Taral" },
{ id: "tasha-holiday", name:"Tasha Holiday" },
{ id: "tayla-parx", name:"Tayla Parx" },
{ id: "teairra-mari", name:"Teairra Mari" },
{ id: "teedra-moses", name:"Teedra Moses" },
{ id: "teena-marie", name:"Teena Marie" },
{ id: "tevin-campbell", name:"Tevin Campbell" },
{ id: "tgt", name:"TGT" },
{ id: "the-boys", name:"The Boys" },
{ id: "the-braxtons", name:"The Braxtons" },
{ id: "the-deele", name:"The Deele" },
{ id: "the-fratz", name:"The Fratz" },
{ id: "the-irvin-lee-project", name:"The Irvin Lee Project" },
{ id: "the-mary-jane-girls", name:"The Mary Jane Girls" },
{ id: "the-pointer-sisters", name:"The Pointer Sisters" },
{ id: "the-dream", name:"The-Dream" },
{ id: "tiara-thomas", name:"Tiara Thomas" },
{ id: "tiffany-evans", name:"Tiffany Evans" },
{ id: "tiffanyj", name:"TiffanyJ" },
{ id: "tina-turner", name:"Tina Turner" },
{ id: "tinashe", name:"Tinashe" },
{ id: "tink", name:"Tink" },
{ id: "tisha-campbell", name:"Tisha Campbell" },
{ id: "tlc", name:"TLC" },
{ id: "toni-braxton", name:"Toni Braxton" },
{ id: "tony-thompson", name:"Tony Thompson" },
{ id: "tony!-toni!-tone!", name:"Tony! Toni! Tone!" },
{ id: "total", name:"Total" },
{ id: "tq", name:"TQ" },
{ id: "tracie-spencer", name:"Tracie Spencer" },
{ id: "trellini", name:"Trellini" },
{ id: "trey-songz", name:"Trey Songz" },
{ id: "trina-&-tamara", name:"Trina & Tamara" },
{ id: "trisha-covington", name:"Trisha Covington" },
{ id: "troop", name:"Troop" },
{ id: "troy-hinton", name:"Troy Hinton" },
{ id: "truth-hurts", name:"Truth Hurts" },
{ id: "tweet-", name:"Tweet " },
{ id: "twelve-a.m.", name:"Twelve A.M." },
{ id: "ty-dolla-$ign", name:"Ty Dolla $ign" },
{ id: "tyneshi-keli", name:"Tyneshi Keli" },
{ id: "tyra-b.", name:"Tyra B." },
{ id: "tyrese", name:"Tyrese" },
{ id: "u-mynd", name:"U-Mynd" },
{ id: "u.n.v.", name:"U.N.V." },
{ id: "urban-mystic", name:"Urban Mystic" },
{ id: "usher", name:"Usher" },
{ id: "v.a.-(very-artistic)", name:"V.A. (Very Artistic)" },
{ id: "vanessa-marquez", name:"Vanessa Marquez" },
{ id: "vanessa-williams", name:"Vanessa Williams" },
{ id: "vega", name:"Vega" },
{ id: "verse-simmonds", name:"Verse Simmonds" },
{ id: "vertical-hold", name:"Vertical Hold" },
{ id: "victoria-monet", name:"Victoria Monet" },
{ id: "virginia", name:"Virginia" },
{ id: "vistoso-bosses", name:"Vistoso Bosses" },
{ id: "vivian-green", name:"Vivian Green" },
{ id: "voices", name:"Voices" },
{ id: "vybe", name:"Vybe" },
{ id: "wayne-wonder", name:"Wayne Wonder" },
{ id: "whitehead-bros.", name:"Whitehead Bros." },
{ id: "whitney-houston", name:"Whitney Houston" },
{ id: "will-downing", name:"Will Downing" },
{ id: "willie-max", name:"Willie Max" },
{ id: "wiremu", name:"Wiremu" },
{ id: "xavier", name:"Xavier" },
{ id: "xl", name:"XL" },
{ id: "xplicit", name:"Xplicit" },
{ id: "xscape", name:"Xscape" },
{ id: "y?-n-vee", name:"Y?-n-Vee" },
{ id: "yasmeen", name:"Yasmeen" },
{ id: "young-debarge", name:"Young Debarge" },
{ id: "yvette-michelle", name:"Yvette Michelle" },
{ id: "zapp", name:"Zapp" },
];